language: java
sudo: true
dist: trusty
addons:
  sonarcloud:
    organization: alvaro2302-github
    token:
      secure: fd6GXyriwioFsyfFhij1HLRTFq0Lalr0xhG8v1ZYIa/lwySNG2+/usUjcu7lAa9yLRq0/dc91Ek75vaVAQhMZ0T4JRlWHs3kW+6d+3kyUHsHKtHyj82T6IpXtGG3FAUHB7HukY/VxQmmkRMJfjgeGy0uffQObMSMCdfw43huKpAhqmoMpSe4PaPLQFxwzmQtQm5Xrb/iPSAj8FS+yFKP6chfDqb1JSD4hsq7HDArAZD6PkpZM8GBgazyToTrIkSgTlPH55I6i0oWHX/6O7XTttbjyIZ5sPl5AWpAZiJDkV56+a9yYmtfwUunle7fHiacUMNm+y3beGMuI3nIqLLf+SaOm47kYJxSRaF5cD007WQWfmJwakM0BlyOQzcswjfPT7Xs6V5MD8xrtv5yZY1rTXA0Trt+PM4g0A2IRZKvekZauNR23NYGl8zz5Bm+GIQz7jAjBNiZ0iK44XrGt65JrwsIthbjxkzegBY/IgeIrEx2pMPxxPIPprJlGH015npvd38vmDuCzRdQJO1yu9Yss3ML4n+nwt6orqiqIW/tbEReFDTPkRqVD2X4aOrJ2a7eG5tdmJilH2Is8jhWZIiQ64dYF6ShUYyC/xfxliQJzfOJhMl8hRnG2jBZxFMmAgOKH08xiz4wdwmApf5PEhk16oqRThdG34iOf58zSrHJxvk=
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
before_install:
- chmod +x mvnw