language: java
sudo: true
dist: trusty
addons:
  sonarcloud:
    organization: "alvaro2302-github"
    token:
      secure: "mkzAPHld7VnRVpz0PYKl2QMl9Zi1LLZQ0StBPdDeDlrg1xUwpOprNNjg3Vnc1XYjHkTBhpkT4FjZtpybPqtbfSopx5F3X21mIKWeJ694AyfKLb0kZSn/00QvUFtdYZ9hV29ysTP6CBiN5xpnZxtAOLsLzmqBeYNQjMl/1FVp0Q4rDqVjwlnWAe85G+uREXytTuwAPrBBAYWQt2sY0M9n8P8jrAXMXR8nRoUUjgs9csb7wIpZgjfuZyhSg+Y3gFm4MHImz2vjqZz9BwbDJooowhGnFtmexTrWFx4ytpZOlOdYDDTD73tretXXxcGAiveyHLyTk3ASYlMdG/4Ih1c29CVqQua+3mHpkeqKw3aMMVukCw5Yfr08q8DJsrNux7OdcSm67Ch9ypyUypR+Bc658dUMzWeHjqjXiY1Th+pk1cf3qStY79Vm/iYPW/8zPckt+S5ZkjNIGEO7ZAdd3rd10qXmUzMhZcvlA8jSFDbFat2N5BcV/pWDtKb/JUUmgoKKbnYYzGcq7l6U209PtgaDzNPEJSbLHYZ7oUq6sE6Vj0rFNObNwIAJUUdMQ9czL+bnB0eHjR27oZ3UZCNrvj+wNqx9oMmRN578CadwBTOLpoPj4BsmrbrsEasd1GJ3TE5wDPCMEO71QX374hGrpLEFhIQXz8GZqBlhQWypLf7WLJI="

script:
  # other script steps might be done before running the actual analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
before_install:
  - chmod +x mvnw